[tool.robocop]
# include = ['W0504']
# exclude = ["0203"]
# ignore = ["ignore_me.robot"]
# format = "{source}:{line}:{col} [{severity}] {rule_id} {desc} (name)"
# output = "robocop.log"
paths = [
    ".",
]
reports = [
    "all",
]
threshold = "W"
configure = [
    "missing-doc-suite:severity:I",
    "missing-doc-keyword:severity:I",
    "missing-doc-test-case:severity:I",
    "too-many-calls-in-test-case:severity:I",
    "not-allowed-char-in-name:severity:I",
]

[tool.robotidy]
src = [
    ".",
]
overwrite = true
diff = true
spacecount = 4
continuation-indent = 4
# transform = [
#    "SplitTooLongLine",
#    "RenameTestCases",
#    "RenameKeywords",
#    "NormalizeNewLines"
# ]
configure = [
    "SplitTooLongLine:enabled=True",
    "RenameTestCases:enabled=True",
    "RenameKeywords:enabled=True",
    "NormalizeNewLines:enabled=True"
]
