[tool.robotidy]
overwrite = true
diff = true
spacecount = 2
continuation-indent = 4
startline = 10
endline = 20
transform = [
   "DiscardEmptySections:allow_only_comments=True",
   "SplitTooLongLine",
   "RenameTestCases",
   "RenameKeywords"
]
configure = [
    "SplitTooLongLine:split_on_every_arg=False"
]
